FROM alpine:3.4
MAINTAINER sparklyballs

# environment settings
ENV PATH ${PATH}:/root/.cabal/bin

# copy apk key
COPY mitch.tishmack@gmail.com-55881c97.rsa.pub /etc/apk/keys/mitch.tishmack@gmail.com-55881c97.rsa.pub

# install packages
RUN \
 echo "https://s3-us-west-2.amazonaws.com/alpine-ghc/next/8.0" >> /etc/apk/repositories && \
 apk add --no-cache \
	bash \
	binutils \
	cabal \
	g++ \
	gcc \
	ghc \
	ghc-dev \
	git \
	make \
	stack && \

# update cabal and stack
 cabal \
	update && \
 stack \
	update && \

# clone shellcheck repo
 git clone https://github.com/koalaman/shellcheck /usr/src/shellcheck

# compile shellcheck
WORKDIR /usr/src/shellcheck
RUN \
 cabal install --only-dependencies
RUN \
 cabal install
RUN \
 cabal test

# Get shellcheck binary
RUN mkdir -p /package/bin/
RUN cp $(which shellcheck) /package/bin/

# Get shared libraries using magic
RUN mkdir -p /package/lib/
RUN ldd $(which shellcheck) | grep "=> /" | awk '{print $3}' | xargs -I '{}' cp -v '{}' /package/lib/

# Copy shellcheck package out to mounted directory
CMD ["cp", "-avr", "/package", "/mnt/"]

